apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
spec:
  selector:
    app: redis
    role: cache
  clusterIP: 10.14.120.10
  type: clusterIP
  ports:
    name: redis
    port: 6379
    targetPort: 6379
    nodePort: